-   id: validate-sam
    name: validate-sam
    description: Validate SAM templates with sam local.
    entry: validate-sam.sh
    language: script
    files: template.yml
-   id: validate-cf
    name: validate-cf
    description: Validate CloudFormation templates.
    entry: validate-cf.sh
    language: script
-   id: lint-cf
    name: lint-cf
    description: Lint Cloudformation templates.
    entry: lint-cf.sh
